--EM CHƯA LÀM ĐƯỢC PHẦN THÊM RÀNG BUỘC THULAOTONG = THULAO*THULAIGIO


use master
go

CREATE DATABASE QUANLY
go

USE QUANLY
GO

CREATE TABLE NHANVIEN(
	MANV nvarchar(50) primary key not null,
	HOTEN nvarchar(100) not null,
	NGSINH DATETIME CHECK(GETDATE()-NGSINH>18),
	NGAYKYHD DATETIME,
	DCHI nvarchar(300) not null,
	PHAI nvarchar(50),
	LUONG money CHECK(Luong>1000),
	MA_NQL NVARCHAR(50) not null,
	PHG nvarchar(50) not null
)
GO




CREATE TABLE DEAN(
	MADA int IDENTITY(3,2) PRIMARY KEY,
	TENDA nvarchar(300) UNIQUE NOT NULL,
	DDIEM_DA nvarchar(100) CHECK (DDIEM_DA IN (N'Hà Nội',N'Hải Phòng',N'TP.HCM')),
	PHONG nvarchar(30) NOT NULL
)
GO

CREATE TABLE PHONGBAN(
	MAPHG INT IDENTITY(1,1) PRIMARY KEY,
	TENPNG NVARCHAR(50),
	TRPHG NVARCHAR(100) NOT NULL,
	NG_NHANCHUC DATE NOT NULL
)
GO


CREATE TABLE CONGVIEC(
	MADA INT NOT NULL,
	STT INT UNIQUE CHECK(STT>1),
	TEN_CONG_VIEC NVARCHAR(300) NOT NULL
)
GO

CREATE TABLE PHANCONG(
	MANV nvarchar(50) NOT NULL,
	MADA INT NOT NULL,
	STT INT NOT NULL,
	THOIGIAN FLOAT,
	THULAOGIO MONEY
)
GO

-----THÊM RÀNG BUỘC----

ALTER TABLE PHANCONG
ADD CONSTRAINT rb1
CHECK (THOIGIAN>1)
GO

ALTER TABLE PHANCONG
ADD CONSTRAINT rb2
CHECK (THULAOGIO>200 AND THULAOGIO<400)
GO


ALTER TABLE NHANVIEN
ADD CONSTRAINT rb3
CHECK (PHAI=N'Nam' or PHAI = N'Nữ' )
GO

ALTER TABLE PHANCONG
ADD CONSTRAINT rb4
CHECK (THOIGIAN>1)
GO

ALTER TABLE PHANCONG
ADD THULAOTONG MONEY 
GO
UPDATE PHANCONG
SET THULAOTONG = THOIGIAN*THULAOGIO
WHERE THULAOTONG IS NULL
GO

ALTER TABLE CONGVIEC
ADD NGAYBD DATE,
	NGAYKT DATE
GO

ALTER TABLE CONGVIEC
ADD CONSTRAINT rb6 CHECK(NGAYKT>NGAYBD)
GO

INSERT INTO NHANVIEN (MANV,HOTEN,NGSINH,NGAYKYHD,DCHI,PHAI,LUONG,MA_NQL,PHG)
VALUES ('NV1',N'Mai Việt Đức','09-08-1999','09-08-2014',N'Hà Nội',N'Nam',200000,'QL1','Phong1')
INSERT INTO NHANVIEN (MANV,HOTEN,NGSINH,NGAYKYHD,DCHI,PHAI,LUONG,MA_NQL,PHG)
VALUES ('NV2',N'Mai Việt Đức1','09-08-1999','09-08-2014',N'Hà Nội',N'Nữ',300000,'QL1',N'Phòng 2')
INSERT INTO NHANVIEN (MANV,HOTEN,NGSINH,NGAYKYHD,DCHI,PHAI,LUONG,MA_NQL,PHG)
VALUES ('NV3',N'Mai Việt Đức2','09-08-1999','09-08-2014',N'Hà Nội',N'Nam',400000,'QL1',N'Phòng 3')
INSERT INTO NHANVIEN (MANV,HOTEN,NGSINH,NGAYKYHD,DCHI,PHAI,LUONG,MA_NQL,PHG)
VALUES ('NV4',N'Mai Việt Đức1','09-08-1999','09-08-2014',N'Hà Nội',N'Nữ',300000,'NV1',N'Phòng 2')
INSERT INTO NHANVIEN (MANV,HOTEN,NGSINH,NGAYKYHD,DCHI,PHAI,LUONG,MA_NQL,PHG)
VALUES ('NV5',N'Mai Việt Đức2','09-08-1999','09-08-2014',N'Hà Nội',N'Nam',400000,'NV1',N'Phòng 3')

select * from NHANVIEN

INSERT INTO DEAN (TENDA,DDIEM_DA,PHONG)
VALUES (N'Đề án 1', N'Hà Nội', N'Phòng 1')
INSERT INTO DEAN (TENDA,DDIEM_DA,PHONG)
VALUES (N'Đề án 2', N'Hà Nội', N'Phòng 2')
INSERT INTO DEAN (TENDA,DDIEM_DA,PHONG)
VALUES (N'Đề án 3', N'Hà Nội', N'Phòng 3')
GO
SELECT * FROM DEAN

INSERT INTO PHONGBAN (TENPNG,TRPHG,NG_NHANCHUC)
VALUES (N'Phòng 1', N'Mai Việt Đức' ,'09-09-2015')
INSERT INTO PHONGBAN (TENPNG,TRPHG,NG_NHANCHUC)
VALUES (N'Phòng 2', N'Mai Việt Đức' ,'08-09-2015')
INSERT INTO PHONGBAN (TENPNG,TRPHG,NG_NHANCHUC)
VALUES (N'Phòng 3', N'Mai Việt Đức' ,'07-09-2015')
SELECT * FROM PHONGBAN
GO

INSERT INTO CONGVIEC (MADA,STT,TEN_CONG_VIEC,NGAYBD,NGAYKT)
VALUES (3,2,N'Việc 1','02-02-2021','02-05-2021')
INSERT INTO CONGVIEC (MADA,STT,TEN_CONG_VIEC,NGAYBD,NGAYKT)
VALUES (5,3,N'Việc 2','02-02-2021','02-05-2021')
INSERT INTO CONGVIEC (MADA,STT,TEN_CONG_VIEC,NGAYBD,NGAYKT)
VALUES (7,4,N'Việc 3','02-02-2021','02-05-2021')
GO

SELECT *FROM CONGVIEC

INSERT INTO PHANCONG(MANV,MADA,STT,THOIGIAN,THULAOGIO)
VALUES ('NV1', 3, 2, 3,300)
INSERT INTO PHANCONG(MANV,MADA,STT,THOIGIAN,THULAOGIO)
VALUES ('NV2', 5, 3, 3,300)
INSERT INTO PHANCONG(MANV,MADA,STT,THOIGIAN,THULAOGIO)
VALUES ('NV3', 7, 4, 3,300)

UPDATE PHANCONG
SET THULAOTONG = THOIGIAN*THULAOGIO
WHERE THULAOTONG IS NULL

SELECT *FROM PHANCONG


CREATE TABLE THONG_KE_CONG_VIEC(
	MANV NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	TONGSODA INT ,
	TONGTHULAO MONEY,
	TENPHONG NVARCHAR(50)
)

INSERT INTO THONG_KE_CONG_VIEC(MANV,HOTEN,TONGSODA,TONGTHULAO, TENPHONG)
VALUES ('NV1', N'Mai Việt Đức',3,4000,N'Phong1')
INSERT INTO THONG_KE_CONG_VIEC(MANV,HOTEN,TONGSODA,TONGTHULAO,TENPHONG)
VALUES ('NV2', N'Mai Việt Đức1',3,4000,N'Phòng 2')
INSERT INTO THONG_KE_CONG_VIEC(MANV,HOTEN,TONGSODA,TONGTHULAO,TENPHONG)
VALUES ('NV3', N'Mai Việt Đức2',3,4000,N'Phòng 3')



------------------------------------------------------------
-------a----
SELECT a.MANV, a.HOTEN,
CASE
	WHEN b.HOTEN = NULL THEN 'KHONG CO'
END AS 'HOTENQUANLY'
FROM NHANVIEN a LEFT join NHANVIEN b on a.MANV=b.MA_NQL

GROUP BY A.MANV, A.HOTEN, B.HOTEN


----------
SELECT N.MANV,N.HOTEN, DATEDIFF(YEAR ,N.NGSINH , GETDATE()) AS 'TUOI', D.DDIEM_DA
FROM NHANVIEN N JOIN DEAN D ON N.PHG = D.PHONG
WHERE D.DDIEM_DA = N'Hà Nội'


-----------------

SELECT N.MANV,N.HOTEN, COUNT(D.MADA) AS 'SO DE AN THAM GIA'
FROM NHANVIEN N JOIN DEAN D ON N.PHG = D.PHONG
WHERE D.PHONG = N'Phòng 2' 
GROUP BY N.MANV,N.HOTEN 
HAVING COUNT(D.MADA) >3

-----------------

SELECT N.MANV, N.HOTEN , SUM(P.THULAOTONG)
FROM PHANCONG P JOIN NHANVIEN N ON N.MANV = P.MANV
JOIN CONGVIEC C ON P.MADA=C.MADA
WHERE C.NGAYKT <= '12-30-2010'
GROUP BY N.MANV, N.HOTEN 


------------

SELECT HOTEN, DATEADD(YEAR, 5, NGAYKYHD)
FROM NHANVIEN

--------------

SELECT D.TENDA
FROM DEAN D JOIN NHANVIEN N ON D.PHONG = N.PHG
GROUP BY D.TENDA
HAVING COUNT(N.MA_NQL)>5

